### ISSUE TITLE
Errors are hidden and captured at a high level

### ISSUE THREAD

**Issue by DaveChamberlain** [DaveChamberlain/casim#10]
As a user, when I start the simulator by double-clicking, any errors may be hidden by the jar file (which opens without the java console).  However, if I open it from the command line with:
     java -jar simulator.jar
and don't have any settings, I see:
java.io.FileNotFoundException: settings.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at simulator.BootGUI.<init>(BootGUI.java:124)
	at simulator.Computer.initialize(Computer.java:181)
	at simulator.Computer.startComputer(Computer.java:168)
	at simulator.Computer.<init>(Computer.java:156)
	at simulator.Computer.main(Computer.java:374)

In the code, some errors, such as the file not existing, are fine!  But they're being caught with a base class.

**Comment by andrea-couto** [comment]
fixed with issue 15 in casim-15

**Comment by DaveChamberlain** [comment]
It's more of a general statement.  There are `catch Exception` statements all over the place that spit out stack traces.  Some of them are bogus and not real errors while others are real.  Should try to determine what is being caught and handle the specific cases rather than a global exception handler that doesn't really do anything but a trace.
